default: BankAccount.class SavingsAccount.class ATMMachine.class

BankAccount.class: BankAccount.java
	javac BankAccount.java

SavingsAccount.class: SavingsAccount.java
	javac SavingsAccount.java

ATMMachine.class: ATMMachine.java
	javac ATMMachine.java

clean:
	rm *.class 

run: 
	java ATMMachine
